import DauCore
import Foundation

/// Loads the bundled inventory and reference contours once, at launch.
///
/// Both files are generated by `ios/tools/build-content.sh` from the repo's own authoring
/// source, so a decode failure here is a build bug rather than a runtime condition — hence
/// the hard failure rather than a fallback that would quietly ship an app with no words in it.
@Observable
final class ContentStore {
    let content: DauContent
    /// Swift-computed reference contours, keyed "<accent>/<wordID>".
    ///
    /// Recomputed with `PitchFrameAnalyzer` at build time on purpose: the learner's contour
    /// comes from that same code, and comparing it against a librosa-derived target would
    /// read estimator disagreement as learner error — and put that difference straight into
    /// the shape-match number.
    private let references: [String: [Double]]

    init(bundle: Bundle = .main) {
        guard let contentURL = bundle.url(
            forResource: "dau-content-v1", withExtension: "json", subdirectory: "Content"
        ), let data = try? Data(contentsOf: contentURL),
           let decoded = try? DauContent.decode(from: data) else {
            fatalError("dau-content-v1.json missing or stale — run ios/tools/build-content.sh")
        }
        self.content = decoded

        var references: [String: [Double]] = [:]
        if let referenceURL = bundle.url(
            forResource: "reference-contours-v1", withExtension: "json", subdirectory: "Content"
        ), let data = try? Data(contentsOf: referenceURL),
           let rows = try? JSONDecoder().decode([ReferenceRow].self, from: data) {
            for row in rows { references["\(row.accent)/\(row.wordID)"] = row.contour }
        }
        self.references = references
    }

    private struct ReferenceRow: Decodable {
        let wordID: String
        let accent: String
        let contour: [Double]
    }

    /// The target contour to draw and to measure shape match against, if one exists.
    ///
    /// Nil for the two Southern words whose generation failed (`ma-grave`,
    /// `phuong-phoenix`). The UI says so plainly rather than hiding the gap — the rule
    /// verdict is pitch-only and still works without a reference.
    func referenceContour(word: String, accent: Accent) -> [Double]? {
        references["\(accent.rawValue)/\(word)"]
    }

    func referenceAudioURL(word: String, accent: Accent, bundle: Bundle = .main) -> URL? {
        bundle.url(
            forResource: word, withExtension: "m4a",
            subdirectory: "Content/targets/\(accent.rawValue)"
        )
    }

    /// Words in the order the first-run queue wants them — the six-ma set first, where
    /// verdicts are strongest and most nameable.
    var featuredWords: [DauContent.Word] {
        content.featuredQueue.compactMap { content.word(id: $0) }
    }

    /// The six meanings of `ma`: one sound, six meanings. The product's map.
    var sixMaWords: [DauContent.Word] {
        guard let group = content.sixMaGroup() else { return [] }
        return group.wordIDs.compactMap { content.word(id: $0) }
    }
}
